### ISSUE TITLE
"Internal server error" after GitHub auth

### ISSUE THREAD

**Issue by walro** [Starkast/wikimum#119]
Flow:

1. Being on https://starkast.wiki/geekbench_4
2. Clicking on "Authorize (GitHub)
3. Internal Server Error

I get stuck at https://starkast.wiki/authorize/callback/geekbench_4?code=[some_hex]

**Comment by dentarg** [comment]
Sentry issue: [WIKI-E](https://sentry.io/starkast/wiki/issues/870716975/?referrer=github_plugin)

```
KeyError: key not found: :ciphers
  from restclient/request.rb:163:in `fetch'
  from restclient/request.rb:163:in `initialize'
  from restclient/request.rb:41:in `new'
  from restclient/request.rb:41:in `execute'
  from restclient.rb:69:in `post'
  from /app/lib/services/authorize.rb:12:in `access_token'
  from /app/lib/controllers/authorize_controller.rb:17:in `block in <class:AuthorizeController>'
  from sinatra/base.rb:1635:in `call'
  from sinatra/base.rb:1635:in `block in compile!'
  from sinatra/base.rb:992:in `block (3 levels) in route!'
  from sinatra/base.rb:1011:in `route_eval'
  from sinatra/base.rb:992:in `block (2 levels) in route!'
  from sinatra/base.rb:1040:in `block in process_route'
  from sinatra/base.rb:1038:in `catch'
  from sinatra/base.rb:1038:in `process_route'
  from sinatra/base.rb:990:in `block in route!'
  from sinatra/base.rb:989:in `each'
  from sinatra/base.rb:989:in `route!'
  from sinatra/base.rb:1097:in `block in dispatch!'
  from sinatra/base.rb:1076:in `block in invoke'
  from sinatra/base.rb:1076:in `catch'
  from sinatra/base.rb:1076:in `invoke'
  from sinatra/base.rb:1094:in `dispatch!'
  from sinatra/base.rb:924:in `block in call!'
  from sinatra/base.rb:1076:in `block in invoke'
  from sinatra/base.rb:1076:in `catch'
  from sinatra/base.rb:1076:in `invoke'
  from sinatra/base.rb:924:in `call!'
  from sinatra/base.rb:913:in `call'
  from rack/flash.rb:124:in `call'
  from rack/protection/xss_header.rb:18:in `call'
  from rack/protection/path_traversal.rb:16:in `call'
  from rack/protection/json_csrf.rb:26:in `call'
  from rack/protection/base.rb:50:in `call'
  from rack/protection/base.rb:50:in `call'
  from rack/protection/frame_options.rb:31:in `call'
  from rack/logger.rb:15:in `call'
  from rack/common_logger.rb:33:in `call'
  from sinatra/base.rb:231:in `call'
  from sinatra/base.rb:224:in `call'
  from rack/head.rb:12:in `call'
  from sinatra/base.rb:194:in `call'
  from sinatra/base.rb:1958:in `call'
  from sinatra/base.rb:1502:in `block in call'
  from sinatra/base.rb:1729:in `synchronize'
  from sinatra/base.rb:1502:in `call'
  from rack/urlmap.rb:68:in `block in call'
  from rack/urlmap.rb:53:in `each'
  from rack/urlmap.rb:53:in `call'
  from rack/static.rb:149:in `call'
  from rack/session/abstract/id.rb:232:in `context'
  from rack/session/abstract/id.rb:226:in `call'
  from rack/ssl.rb:27:in `call'
  from raven/integrations/rack.rb:50:in `call'
  from puma/configuration.rb:225:in `call'
  from puma/server.rb:658:in `handle_request'
  from puma/server.rb:472:in `process_client'
  from puma/server.rb:332:in `block in run'
  from puma/thread_pool.rb:133:in `block in spawn_thread'
```
