### ISSUE TITLE
New Relic "WARNING: Detected 2 Thread(s) started in app boot"

### ISSUE THREAD

**Issue by dentarg** [Starkast/wikimum#41]
When starting:

```
2015-12-06T00:20:25.417334+00:00 heroku[web.1]: State changed from up to starting
2015-12-06T00:20:32.240060+00:00 heroku[web.1]: Starting process with command `bundle exec puma -C config/puma.rb`
2015-12-06T00:20:34.208008+00:00 app[web.1]: [3] Puma starting in cluster mode...
2015-12-06T00:20:34.208037+00:00 app[web.1]: [3] * Version 2.14.0 (ruby 2.2.3-p173), codename: Fuchsia Friday
2015-12-06T00:20:34.208038+00:00 app[web.1]: [3] * Min threads: 1, max threads: 16
2015-12-06T00:20:34.208039+00:00 app[web.1]: [3] * Environment: production
2015-12-06T00:20:34.208039+00:00 app[web.1]: [3] * Process workers: 3
2015-12-06T00:20:34.208039+00:00 app[web.1]: [3] * Preloading application
2015-12-06T00:20:35.186293+00:00 heroku[web.1]: State changed from starting to up
2015-12-06T00:20:35.021464+00:00 app[web.1]: ** [NewRelic][12/06/15 00:20:35 +0000 web.1 (3)] INFO : Installing Net instrumentation
2015-12-06T00:20:35.026423+00:00 app[web.1]: ** [NewRelic][12/06/15 00:20:35 +0000 web.1 (3)] INFO : Finished instrumentation
2015-12-06T00:20:35.036303+00:00 app[web.1]: [3] * Listening on tcp://0.0.0.0:50841
2015-12-06T00:20:35.036394+00:00 app[web.1]: [3] ! WARNING: Detected 2 Thread(s) started in app boot:
2015-12-06T00:20:35.036482+00:00 app[web.1]: [3] ! #<Thread:0x007f45b8b1edd8@/app/vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.13.1.300/lib/new_relic/agent/threading/agent_thread.rb:12 sleep> - /app/vendor/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'
2015-12-06T00:20:35.036509+00:00 app[web.1]: [3] ! #<Thread:0x007f45b899ade0@/app/vendor/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:79 sleep> - /app/vendor/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:81:in `sleep'
2015-12-06T00:20:35.036573+00:00 app[web.1]: [3] Use Ctrl-C to stop
2015-12-06T00:20:35.040665+00:00 app[web.1]: [3] - Worker 0 (pid: 8) booted, phase: 0
2015-12-06T00:20:35.042561+00:00 app[web.1]: [3] - Worker 2 (pid: 19) booted, phase: 0
2015-12-06T00:20:34.986392+00:00 app[web.1]: ** [NewRelic][12/06/15 00:20:34 +0000 web.1 (3)] INFO : Starting the New Relic agent in "production" environment.
2015-12-06T00:20:34.986401+00:00 app[web.1]: ** [NewRelic][12/06/15 00:20:34 +0000 web.1 (3)] INFO : To prevent agent startup add a NEWRELIC_AGENT_ENABLED=false environment variable or modify the "production" section of your newrelic.yml.
2015-12-06T00:20:34.986433+00:00 app[web.1]: ** [NewRelic][12/06/15 00:20:34 +0000 web.1 (3)] WARN : No configuration file found. Working directory = /app
2015-12-06T00:20:34.986454+00:00 app[web.1]: ** [NewRelic][12/06/15 00:20:34 +0000 web.1 (3)] WARN : Looked in these locations (based on defaults): /app/config/newrelic.yml, /app/newrelic.yml, /app/config/newrelic.yml, /app/newrelic.yml, /app/.newrelic/newrelic.yml, /app/newrelic.yml
2015-12-06T00:20:34.987772+00:00 app[web.1]: ** [NewRelic][12/06/15 00:20:34 +0000 web.1 (3)] INFO : Environment: production
2015-12-06T00:20:34.987777+00:00 app[web.1]: ** [NewRelic][12/06/15 00:20:34 +0000 web.1 (3)] INFO : Dispatcher: Puma
2015-12-06T00:20:34.987819+00:00 app[web.1]: ** [NewRelic][12/06/15 00:20:34 +0000 web.1 (3)] INFO : Application: wikimum
2015-12-06T00:20:35.020240+00:00 app[web.1]: ** [NewRelic][12/06/15 00:20:35 +0000 web.1 (3)] INFO : Installing Sequel instrumentation
2015-12-06T00:20:35.023101+00:00 app[web.1]: ** [NewRelic][12/06/15 00:20:35 +0000 web.1 (3)] INFO : Installing deferred Rack instrumentation
2015-12-06T00:20:35.023191+00:00 app[web.1]: ** [NewRelic][12/06/15 00:20:35 +0000 web.1 (3)] INFO : Installing Rack::Builder middleware instrumentation
2015-12-06T00:20:35.023942+00:00 app[web.1]: ** [NewRelic][12/06/15 00:20:35 +0000 web.1 (3)] INFO : Installing Sinatra instrumentation
2015-12-06T00:20:35.032208+00:00 app[web.1]: ** [NewRelic][12/06/15 00:20:35 +0000 web.1 (3)] INFO : Doing deferred dependency-detection before Rack startup
2015-12-06T00:20:35.041156+00:00 app[web.1]: [3] - Worker 1 (pid: 12) booted, phase: 0
```

logs continue to show:

```
2015-12-06T00:20:35.823699+00:00 app[web.1]: ** [NewRelic][12/06/15 00:20:35 +0000 web.1 (19)] WARN : Ignoring addition of cpu because it is already registered.
2015-12-06T00:20:35.823764+00:00 app[web.1]: ** [NewRelic][12/06/15 00:20:35 +0000 web.1 (19)] WARN : Ignoring addition of memory because it is already registered.
2015-12-06T00:20:35.823857+00:00 app[web.1]: ** [NewRelic][12/06/15 00:20:35 +0000 web.1 (19)] WARN : Ignoring addition of vm because it is already registered.
```

**Comment by dentarg** [comment]
Related issues in other projects:

* https://github.com/puma/puma/issues/614
* https://github.com/twingly/ganges/issues/38
* https://github.com/twingly/chuma/issues/63
* https://github.com/zooniverse/Panoptes/issues/1497

Workarounds

* https://github.com/Tomohiro/plate/commit/0a5a072c8d882f32a48d8bdbfa325e83719f58f8
* https://github.com/zooniverse/Panoptes/pull/1498/files
