### ISSUE TITLE
"Thread.exclusive is deprecated, use Mutex"

### ISSUE THREAD

**Issue by dentarg** [Starkast/wikimum#61]
Seen in development:

```
15:48:47 web.1  | [98104] - Worker 1 (pid: 98112) booted, phase: 0
15:48:47 web.1  | [98104] - Worker 2 (pid: 98113) booted, phase: 0
15:48:47 web.1  | [98104] - Worker 0 (pid: 98111) booted, phase: 0
15:49:32 web.1  | Thread.exclusive is deprecated, use Mutex
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/sinatra-contrib-1.4.6/lib/sinatra/reloader.rb:222:in `block in registered'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `block in compile!'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:1014:in `block in process_route'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `catch'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `process_route'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/newrelic_rpm-3.13.1.300/lib/new_relic/agent/instrumentation/sinatra.rb:119:in `process_route_with_newrelic'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:965:in `block in filter!'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:965:in `each'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:965:in `filter!'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:964:in `filter!'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:1083:in `block in dispatch!'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:1081:in `dispatch!'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/newrelic_rpm-3.13.1.300/lib/new_relic/agent/instrumentation/sinatra.rb:164:in `dispatch_and_notice_errors_with_newrelic'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/newrelic_rpm-3.13.1.300/lib/new_relic/agent/instrumentation/sinatra.rb:150:in `block in dispatch_with_newrelic'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/newrelic_rpm-3.13.1.300/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:362:in `perform_action_with_newrelic_trace'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/newrelic_rpm-3.13.1.300/lib/new_relic/agent/instrumentation/sinatra.rb:147:in `dispatch_with_newrelic'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `block in call!'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `call!'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:894:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/newrelic_rpm-3.13.1.300/lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/newrelic_rpm-3.13.1.300/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/newrelic_rpm-3.13.1.300/lib/new_relic/rack/browser_monitoring.rb:32:in `traced_call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/newrelic_rpm-3.13.1.300/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/rack-flash3-1.0.5/lib/rack/flash.rb:124:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/newrelic_rpm-3.13.1.300/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/newrelic_rpm-3.13.1.300/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/newrelic_rpm-3.13.1.300/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/newrelic_rpm-3.13.1.300/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/newrelic_rpm-3.13.1.300/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/newrelic_rpm-3.13.1.300/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/newrelic_rpm-3.13.1.300/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/rack-1.6.4/lib/rack/logger.rb:15:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/newrelic_rpm-3.13.1.300/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/rack-1.6.4/lib/rack/commonlogger.rb:33:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:218:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:211:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/newrelic_rpm-3.13.1.300/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/newrelic_rpm-3.13.1.300/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/sinatra-1.4.6/lib/sinatra/show_exceptions.rb:21:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/newrelic_rpm-3.13.1.300/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:181:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/newrelic_rpm-3.13.1.300/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:2021:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in `block in call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:1795:in `synchronize'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in `block in call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `each'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/rack-1.6.4/lib/rack/static.rb:124:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/sentry-raven-2.4.0/lib/raven/integrations/rack.rb:50:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/puma-2.14.0/lib/puma/commonlogger.rb:31:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/puma-2.14.0/lib/puma/configuration.rb:78:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/puma-2.14.0/lib/puma/server.rb:541:in `handle_request'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/puma-2.14.0/lib/puma/server.rb:388:in `process_client'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/puma-2.14.0/lib/puma/server.rb:270:in `block in run'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/puma-2.14.0/lib/puma/thread_pool.rb:106:in `block in spawn_thread'
15:49:32 web.1  | Thread.exclusive is deprecated, use Mutex
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/sinatra-contrib-1.4.6/lib/sinatra/reloader.rb:222:in `block in registered'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `block in compile!'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:1014:in `block in process_route'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `catch'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `process_route'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/newrelic_rpm-3.13.1.300/lib/new_relic/agent/instrumentation/sinatra.rb:119:in `process_route_with_newrelic'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:965:in `block in filter!'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:965:in `each'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:965:in `filter!'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:1083:in `block in dispatch!'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:1081:in `dispatch!'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/newrelic_rpm-3.13.1.300/lib/new_relic/agent/instrumentation/sinatra.rb:164:in `dispatch_and_notice_errors_with_newrelic'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/newrelic_rpm-3.13.1.300/lib/new_relic/agent/instrumentation/sinatra.rb:150:in `block in dispatch_with_newrelic'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/newrelic_rpm-3.13.1.300/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:362:in `perform_action_with_newrelic_trace'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/newrelic_rpm-3.13.1.300/lib/new_relic/agent/instrumentation/sinatra.rb:147:in `dispatch_with_newrelic'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `block in call!'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `call!'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:894:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/newrelic_rpm-3.13.1.300/lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/newrelic_rpm-3.13.1.300/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/newrelic_rpm-3.13.1.300/lib/new_relic/rack/browser_monitoring.rb:32:in `traced_call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/newrelic_rpm-3.13.1.300/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/rack-flash3-1.0.5/lib/rack/flash.rb:124:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/newrelic_rpm-3.13.1.300/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/newrelic_rpm-3.13.1.300/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/newrelic_rpm-3.13.1.300/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/newrelic_rpm-3.13.1.300/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/newrelic_rpm-3.13.1.300/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/newrelic_rpm-3.13.1.300/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/newrelic_rpm-3.13.1.300/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/rack-1.6.4/lib/rack/logger.rb:15:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/newrelic_rpm-3.13.1.300/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/rack-1.6.4/lib/rack/commonlogger.rb:33:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:218:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:211:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/newrelic_rpm-3.13.1.300/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/newrelic_rpm-3.13.1.300/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/sinatra-1.4.6/lib/sinatra/show_exceptions.rb:21:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/newrelic_rpm-3.13.1.300/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:181:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/newrelic_rpm-3.13.1.300/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:2021:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in `block in call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:1795:in `synchronize'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in `block in call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `each'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/rack-1.6.4/lib/rack/static.rb:124:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/sentry-raven-2.4.0/lib/raven/integrations/rack.rb:50:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/puma-2.14.0/lib/puma/commonlogger.rb:31:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/puma-2.14.0/lib/puma/configuration.rb:78:in `call'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/puma-2.14.0/lib/puma/server.rb:541:in `handle_request'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/puma-2.14.0/lib/puma/server.rb:388:in `process_client'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/puma-2.14.0/lib/puma/server.rb:270:in `block in run'
15:49:32 web.1  | /Users/dentarg/.gem/ruby/2.3.3/gems/puma-2.14.0/lib/puma/thread_pool.rb:106:in `block in spawn_thread'
15:49:32 web.1  | I, [2017-05-13T15:49:32.384544 #98112]  INFO -- : (0.000359s) SET standard_conforming_strings = ON
15:49:32 web.1  | I, [2017-05-13T15:49:32.385300 #98112]  INFO -- : (0.000277s) SET client_min_messages = 'WARNING'
15:49:32 web.1  | I, [2017-05-13T15:49:32.385730 #98112]  INFO -- : (0.000127s) SET DateStyle = 'ISO'
15:49:32 web.1  | I, [2017-05-13T15:49:32.396734 #98112]  INFO -- : (0.010745s) SELECT * FROM "pages" ORDER BY "id" LIMIT 1
15:49:32 web.1  | views/page/show.haml:-5: warning: instance variable @haml_buffer not initialized
15:49:32 web.1  | views/page/../layouts/_navigation.haml:3: warning: instance variable @q not initialized
15:49:32 web.1  | I, [2017-05-13T15:49:32.435455 #98112]  INFO -- : (0.018649s) SELECT * FROM "users" WHERE "id" = 1
15:49:32 web.1  | 127.0.0.1 - - [13/May/2017:15:49:32 +0200] "GET / HTTP/1.1" 200 4419 0.0805
15:49:32 web.1  | [98112] 127.0.0.1 - - [13/May/2017:15:49:32 +0200] "GET / HTTP/1.1" 200 4419 1.8220
15:49:32 web.1  | [98112] 127.0.0.1 - - [13/May/2017:15:49:32 +0200] "GET /stylesheets/default.css HTTP/1.1" 200 6499 0.0026
15:49:32 web.1  | [98112] 127.0.0.1 - - [13/May/2017:15:49:32 +0200] "GET /javascripts/mousetrap.min.js HTTP/1.1" 200 3850 0.0017
15:49:32 web.1  | [98112] 127.0.0.1 - - [13/May/2017:15:49:32 +0200] "GET /javascripts/mousetrap-global-bind.min.js HTTP/1.1" 200 239 0.0009
15:49:32 web.1  | [98112] 127.0.0.1 - - [13/May/2017:15:49:32 +0200] "GET /favicon.ico HTTP/1.1" 200 1406 0.0012
```

**Comment by dentarg** [comment]
Fix is to update sinatra-contrib: https://github.com/sinatra/sinatra-contrib/issues/183
