### ISSUE TITLE
NoMethodError: undefined method `fetch' for #<Page:0x000055d0b9436d60>

### ISSUE THREAD

**Issue by jage** [Starkast/wikimum#73]
https://sentry.io/starkast/wiki/issues/492301922/

```
NoMethodError: undefined method `fetch' for #<Page:0x000055d0b9436d60>
  tilt/template.rb:170:in `call'
    method.bind(scope).call(locals, &block)
  tilt/template.rb:170:in `evaluate'
    method.bind(scope).call(locals, &block)
  tilt/haml.rb:24:in `evaluate'
    super
  tilt/template.rb:109:in `render'
    evaluate(scope, locals || {}, &block)
  sinatra/base.rb:823:in `render'
    output          = template.render(scope, locals, &block)
...
(80 additional frame(s) were not displayed)

NoMethodError: undefined method `fetch' for #<Page:0x000055d0b9436d60>
```

**Comment by jage** [comment]
I think [this change](https://github.com/jeremyevans/sequel/blob/c784c851282ac64984168bbc0d8fb2a292e46907/CHANGELOG#L983) broke this. Sounds like we were relying on a "bug".
